-- STORE-DELETE-01: a file a deleted person shared survives them, but the
-- conversation and turn it arrived in are erased, so both references become
-- nullable. Generated by drizzle-kit; the share-pointer stash below is added
-- by hand: drizzle's migrator runs inside one transaction, where
-- PRAGMA foreign_keys=OFF is a no-op, and dropping `attachments` while
-- `shares` rows point at it fails the foreign key check. The pointers are
-- copied aside, the table is rebuilt, and they are put back unchanged.
PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__store_delete_shares` AS SELECT * FROM `shares`;--> statement-breakpoint
DELETE FROM `shares`;--> statement-breakpoint
CREATE TABLE `__new_attachments` (
	`id` text PRIMARY KEY NOT NULL,
	`owner_person_id` text NOT NULL,
	`conversation_id` text,
	`turn_id` text,
	`media_type` text NOT NULL,
	`size` integer NOT NULL,
	`sha256` text NOT NULL,
	`storage_path` text NOT NULL,
	`retention` text DEFAULT 'conversation' NOT NULL,
	`provenance` text NOT NULL,
	`created_at` text NOT NULL,
	`hlc` text NOT NULL,
	FOREIGN KEY (`owner_person_id`) REFERENCES `people`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`conversation_id`) REFERENCES `conversations`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`turn_id`) REFERENCES `conversation_turns`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
INSERT INTO `__new_attachments`("id", "owner_person_id", "conversation_id", "turn_id", "media_type", "size", "sha256", "storage_path", "retention", "provenance", "created_at", "hlc") SELECT "id", "owner_person_id", "conversation_id", "turn_id", "media_type", "size", "sha256", "storage_path", "retention", "provenance", "created_at", "hlc" FROM `attachments`;--> statement-breakpoint
DROP TABLE `attachments`;--> statement-breakpoint
ALTER TABLE `__new_attachments` RENAME TO `attachments`;--> statement-breakpoint
INSERT INTO `shares`("id", "file_id", "from_person_id", "to", "provenance", "created_at", "hlc") SELECT "id", "file_id", "from_person_id", "to", "provenance", "created_at", "hlc" FROM `__store_delete_shares`;--> statement-breakpoint
DROP TABLE `__store_delete_shares`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
CREATE INDEX `attachments_owner_person_id_idx` ON `attachments` (`owner_person_id`);--> statement-breakpoint
CREATE INDEX `attachments_conversation_id_idx` ON `attachments` (`conversation_id`);--> statement-breakpoint
CREATE INDEX `attachments_turn_id_idx` ON `attachments` (`turn_id`);--> statement-breakpoint
CREATE INDEX `attachments_sha256_idx` ON `attachments` (`sha256`);
