import { DataClass } from "@maipai/spec/gen/ts/data-class.js";

// Home's data classes, declared once (DATA-LOCATION-00c, docs/dev.md
// "DATA-LOCATION: where the household's data lives"). A class is a folder
// whose contents share one owner, one size and access profile, one
// durability need and one rule for what happens when it is missing. The
// shape is the spec's (`data-class.schema.json`); the list is Home's,
// because commons never holds a product's layout. Every consumer draws
// from this array: lib/paths.ts resolves each class's folder from it, and
// the installer, the Storage page, the mover, describeFolder and the
// backup will read it too (DATA-LOCATION-01x, -02x, -03).
//
// Every `default` equals the layout Home had before locations existed, so
// adopting an existing hub moves no file. Stack owned engine data lives
// with the Stack.
//
// The `degrades` entries are feature codes (the design record gives the
// features in prose; the codes are named here, once).
//
// This file imports nothing from lib/paths.ts: paths.ts imports this.

const GB = 1_000_000_000;

export const DATA_CLASSES: DataClass[] = [
  {
    id: "records",
    title: "Household records",
    help: "Your household's people, memories, conversations and settings. This is the one place nothing else can replace, so put it on a disk you trust and back up.",
    level: "basic",
    default: { base: "root", subpath: "" },
    holds: "hub.db, -wal and -shm; the staged restore and factory-reset files beside it; device-id6.txt",
    size: "MB to a few GB",
    access: "small random writes, fsync on every commit",
    durability: "irreplaceable",
    rebuild: "none",
    sensitive: "biometric",
    needs: ["sqlite", "private"],
    whenMissing: "hold",
    degrades: [],
    move: "offline",
    refetch: false,
    backup: "hot",
  },
  {
    id: "keys",
    title: "Encryption keys",
    help: "The keys that unlock your secrets and face prints. If they are lost, everything they protect becomes unreadable, so keep them on a disk that is always connected.",
    level: "basic",
    default: { base: "root", subpath: "keys" },
    holds: "keystore key files and Keychain markers; the household CA and hub identity keys",
    size: "under 1 MB",
    access: "written once, read at boot",
    durability: "irreplaceable",
    rebuild: "none",
    sensitive: "keys",
    needs: ["private"],
    whenMissing: "hold",
    degrades: [],
    move: "offline",
    refetch: false,
    backup: "kit",
  },
  {
    id: "people-files",
    title: "People's files",
    help: "Photos and files people attach to chats. This can grow large, so it is a good candidate for a bigger disk.",
    level: "basic",
    default: { base: "root", subpath: "people" },
    holds: "each person's uploaded attachments",
    size: "grows, MB to tens of GB",
    access: "written once, read often",
    durability: "irreplaceable",
    rebuild: "none",
    sensitive: "personal",
    needs: [],
    whenMissing: "degrade",
    degrades: ["attachments-view", "attachments-add"],
    move: "offline",
    refetch: false,
    backup: "hot",
  },
  {
    id: "cloned-voices",
    title: "Cloned voices",
    help: "Voice samples people uploaded so Home can speak in their voice. They are biometric, so keep them somewhere private.",
    level: "basic",
    default: { base: "root", subpath: "voice/cloned" },
    holds: "voice samples people uploaded for cloning",
    size: "MB",
    access: "written once, read by the speech engine",
    durability: "irreplaceable",
    rebuild: "none",
    sensitive: "biometric",
    needs: [],
    whenMissing: "degrade",
    degrades: ["cloned-voices"],
    move: "offline",
    refetch: false,
    backup: "hot",
  },
  {
    id: "projects",
    title: "Projects",
    help: "The files your household's projects produce. Runs write in bursts, so a fast disk helps.",
    level: "basic",
    default: { base: "root", subpath: "projects" },
    holds: "each project run's artifact files",
    size: "MB to GB",
    access: "bursts of writes during a run",
    durability: "irreplaceable",
    rebuild: "none",
    sensitive: "personal",
    needs: [],
    whenMissing: "degrade",
    degrades: ["project-runs", "project-files"],
    move: "offline",
    refetch: false,
    backup: "hot",
  },
  {
    id: "packages",
    title: "Package data",
    help: "What installed packages keep: their own files and the versions installed from the store.",
    level: "advanced",
    default: { base: "root", subpath: "packages" },
    holds: "per package: state/ (a package's own files, often SQLite), versions/ (store-installed source), .staging/",
    size: "MB to hundreds of MB",
    access: "small random writes in state/; installs by rename",
    durability: "irreplaceable",
    rebuild: "none",
    sensitive: "personal",
    needs: ["sqlite"],
    whenMissing: "degrade",
    degrades: ["tier1-packages", "store-packages"],
    move: "offline",
    refetch: false,
    backup: "hot",
  },
  {
    id: "models",
    title: "AI models",
    help: "Home does not download or run chat models. MaiPai Stack keeps its own model files in its own data folder.",
    level: "basic",
    default: { base: "root", subpath: "models" },
    holds: "No files managed by Home",
    size: "none",
    access: "unused",
    durability: "rebuildable",
    rebuild: "none",
    sensitive: "none",
    needs: ["large-files"],
    whenMissing: "degrade",
    degrades: ["chat"],
    move: "online",
    refetch: false,
    backup: "exclude",
  },
  {
    id: "engines",
    title: "AI engines",
    help: "Home does not download or run a chat engine. MaiPai Stack keeps its own engines in its own data folder.",
    level: "advanced",
    default: { base: "root", subpath: "engines" },
    holds: "No files managed by Home",
    size: "none",
    access: "unused",
    durability: "rebuildable",
    rebuild: "none",
    sensitive: "none",
    needs: ["exec"],
    whenMissing: "degrade",
    degrades: ["chat"],
    move: "online",
    refetch: false,
    backup: "exclude",
  },
  {
    id: "sidecars",
    title: "Helper programs",
    help: "Small helper programs Home downloads, such as the reference library server.",
    level: "advanced",
    default: { base: "root", subpath: "sidecars" },
    holds: "kiwix-tools binaries",
    size: "tens of MB",
    access: "written once, executed",
    durability: "rebuildable",
    rebuild: "download",
    sensitive: "none",
    needs: ["exec"],
    whenMissing: "degrade",
    degrades: ["reference-search"],
    move: "online",
    refetch: true,
    backup: "exclude",
  },
  {
    id: "reference",
    title: "Reference library",
    help: "Offline encyclopedias and other reference archives. They can run past 100 GB, so many households keep them on a big or external disk.",
    level: "basic",
    default: { base: "root", subpath: "reference" },
    holds: "offline reference archives (ZIM files) and library.xml",
    size: "1 GB to over 100 GB",
    access: "written once, random reads during search",
    durability: "rebuildable",
    rebuild: "download",
    sensitive: "none",
    needs: ["large-files"],
    whenMissing: "degrade",
    degrades: ["reference-search"],
    move: "online",
    refetch: true,
    backup: "library",
  },
  {
    id: "wakeword-models",
    title: "Wake word models",
    help: "The small models that listen for the wake word.",
    level: "advanced",
    default: { base: "root", subpath: "voice/wakewords" },
    holds: "wake-word feature models and detectors",
    size: "MB",
    access: "written once, read at start",
    durability: "rebuildable",
    rebuild: "download",
    sensitive: "none",
    needs: [],
    whenMissing: "degrade",
    degrades: ["wake-word"],
    move: "online",
    refetch: true,
    backup: "exclude",
  },
  {
    id: "stt-models",
    title: "Speech endpointing model",
    help: "The small model Home uses to find utterance boundaries in live speech input.",
    level: "advanced",
    default: { base: "root", subpath: "voice/stt" },
    holds: "Silero voice-activity detection model",
    size: "about 2 MB",
    access: "written once, read at start",
    durability: "rebuildable",
    rebuild: "download",
    sensitive: "none",
    needs: [],
    whenMissing: "degrade",
    degrades: ["voice-input"],
    move: "online",
    refetch: true,
    backup: "exclude",
  },
  {
    id: "vision-models",
    title: "Face recognition models",
    help: "The models used for face detection and recognition in the browser.",
    level: "advanced",
    default: { base: "root", subpath: "vision/models" },
    holds: "face detection and embedding models served to browsers",
    size: "tens of MB",
    access: "written once, read on request",
    durability: "rebuildable",
    rebuild: "download",
    sensitive: "none",
    needs: [],
    whenMissing: "degrade",
    degrades: ["face-recognition", "face-enrollment"],
    move: "online",
    refetch: true,
    backup: "exclude",
  },
  {
    id: "logs",
    title: "Logs",
    help: "Home's own record of what it did, rotated so it stays small.",
    level: "advanced",
    default: { base: "root", subpath: "logs" },
    holds: "the hub's structured logs, rotated",
    size: "up to the rotation cap",
    access: "appends",
    durability: "disposable",
    rebuild: "empty",
    sensitive: "none",
    needs: [],
    whenMissing: "degrade",
    degrades: [],
    move: "online",
    refetch: false,
    backup: "exclude",
  },
  {
    id: "cache",
    title: "Package cache",
    help: "Saved answers from package lookups. Home rebuilds it on its own.",
    level: "expert",
    default: { base: "root", subpath: "cache" },
    holds: "package fetch responses",
    size: "MB",
    access: "small random writes",
    durability: "disposable",
    rebuild: "empty",
    sensitive: "none",
    needs: [],
    whenMissing: "degrade",
    degrades: ["package-widget-data"],
    move: "empty",
    refetch: false,
    backup: "exclude",
  },
  {
    id: "favicons",
    title: "Source icons",
    help: "Small icons for the sources Home shows. Home rebuilds them on its own.",
    level: "expert",
    default: { base: "root", subpath: "favicons" },
    holds: "source icons and their index",
    size: "MB",
    access: "small random writes",
    durability: "disposable",
    rebuild: "empty",
    sensitive: "none",
    needs: [],
    whenMissing: "degrade",
    degrades: ["source-icons"],
    move: "empty",
    refetch: false,
    backup: "exclude",
  },
  {
    id: "runtime",
    title: "Running engines",
    help: "A note of which engines are running right now. Home rewrites it every time an engine starts.",
    level: "expert",
    default: { base: "root", subpath: "local-app" },
    holds: "engine-pids.json, the running engines' process ids",
    size: "bytes",
    access: "rewritten on each engine start",
    durability: "disposable",
    rebuild: "empty",
    sensitive: "none",
    needs: [],
    whenMissing: "degrade",
    degrades: ["engine-orphan-sweep"],
    move: "empty",
    refetch: false,
    backup: "exclude",
  },
  {
    id: "labels",
    title: "Weekly turn exports",
    help: "Weekly exports of conversation turns for tuning, written only when an operator asks for one.",
    level: "expert",
    default: { base: "root", subpath: "labels" },
    holds: "weekly turn-label exports from scripts/bench/labels.ts",
    size: "KB to MB",
    access: "written by an operator's export",
    durability: "rebuildable",
    rebuild: "recompute",
    sensitive: "personal",
    needs: [],
    whenMissing: "degrade",
    degrades: ["label-exports"],
    move: "online",
    refetch: false,
    backup: "exclude",
  },
  {
    id: "backups",
    title: "Backups",
    help: "Your household's encrypted backup archives. Keep them on a different disk from your records, or a backup is no safer than the thing it copies.",
    level: "basic",
    default: { base: "beside-root", subpath: "backups" },
    holds: "the household's encrypted archives",
    size: "grows with retention",
    access: "one large sequential write a night",
    durability: "irreplaceable",
    rebuild: "none",
    sensitive: "personal",
    needs: ["large-files"],
    whenMissing: "degrade",
    degrades: ["backups", "updates", "restores", "offline-moves"],
    move: "online",
    refetch: false,
    backup: "none",
  },
  {
    id: "received-backups",
    title: "Backups from robots and pods",
    help: "Encrypted archives that your robots and pods sent here. They are encrypted with the devices' own keys.",
    level: "advanced",
    default: { base: "beside-root", subpath: "received-backups" },
    holds: "archives robots and pods pushed, encrypted with their own keys",
    size: "grows",
    access: "sequential writes by devices",
    durability: "irreplaceable",
    rebuild: "none",
    sensitive: "personal",
    needs: ["large-files"],
    whenMissing: "degrade",
    degrades: ["device-backup-push"],
    move: "online",
    refetch: false,
    backup: "none",
  },
].map((c) => DataClass.parse({ product: "home", ...c }));

export function dataClassById(id: string): DataClass {
  const found = DATA_CLASSES.find((c) => c.id === id);
  if (!found) throw new Error(`No data class named "${id}" (see lib/dataClasses.ts)`);
  return found;
}
