// Step 9: "redacted diagnostics download with a TO_REDACT list in spec/
// and a test that no secret, address or family name survives it" (plan
// 4.15). See spec/diagnostics/to-redact.json for the category-by-
// category reasoning; this file is the one place that list is actually
// enforced. Built structurally (every field below is deliberately
// chosen, never a fuller dump filtered after the fact) rather than by
// pattern-matching text for anything that looks like a name or address
// after the fact - a regex-based scrub over free text can always miss a
// name it has never seen before; simply never including the field in
// the first place cannot.
import { isNull } from "drizzle-orm";
import { db } from "@/db";
import { people, hubEndpoints, issues, packageStatus } from "@/db/schema";
import { getHubInstanceId } from "@/lib/hubIdentity";
import { CURRENT_SCHEMA_VERSION } from "@/db/schema-version";
import { getRegistry } from "@/lib/settingsRegistry";
import { getHouseholdSettingValue } from "@/lib/settings";
import { storageSummary, type StorageSummary } from "@/lib/storage";
import type { PersonRow } from "@/types";

export interface DiagnosticsReport {
  generatedAt: string;
  schemaVersion: number;
  // Never the hub's own display name (lib/hubIdentity.ts's setHubName()
  // lets an admin type anything, including "The Torres House" - exactly
  // the family-name risk this whole report exists to avoid). instanceId
  // alone is a random UUID nobody chose, safe for support purposes.
  hub: { instanceId: string };
  people: Array<{ id: string; role: string; enabled: boolean; source: string; createdAt: string }>;
  endpointCount: number;
  // Never `title` or `detail`: every current raiseIssue() call site only
  // ever puts internal ids and fixed strings there, but neither is
  // checked against a redaction allowlist the way `people`/`settings`
  // are - a review (2026-09-06) found nothing would stop or even flag
  // the very next raiseIssue() call that embeds an admin-typed value (a
  // NAS mount's label, a hub endpoint's name) from flowing straight into
  // this report. `source`/`key` alone already identify what's broken
  // (e.g. `backup`/`smb` already says "backups to smb are failing")
  // without needing a free-text field this file cannot structurally
  // prove is safe.
  issues: Array<{ source: string; key: string; severity: string; createdAt: string; resolvedAt: string | null }>;
  packages: Array<{ packageId: string; status: string; smokeOk: boolean | null }>;
  settings: Array<{ key: string; value: unknown }>;
  storage: StorageSummary;
}

/** `households` settings only (see to-redact.json's `person_scoped_
 * settings` category), and never a value whose own registry entry is
 * `secret: true` - checked dynamically against the live registry rather
 * than a hand-typed key list, so a new secret key is covered the moment
 * it is declared, not the next time someone remembers to update this
 * file too. */
function redactedHouseholdSettings(): Array<{ key: string; value: unknown }> {
  const registry = getRegistry();
  // requireActor is owner/admin-equivalent for household scope in
  // listValues()'s own access check - diagnostics is always generated by
  // an owner/admin route (routes/storage.ts), so a real actor row is
  // available there; this function is only ever called from that path.
  return registry
    .filter((k) => k.scope === "household")
    .map((k) => {
      const secret = "secret" in k && k.secret === true;
      return { key: k.key, value: secret ? "[redacted]" : readHouseholdValueRaw(k.key) };
    });
}

// A tiny, direct read rather than routing through listValues()'s own
// actor-gated resolution: this file already knows it only ever reads
// household scope (never a person's), and listValues() is shaped around
// "one person's own visible slice," not "every household key at once."
function readHouseholdValueRaw(key: string): unknown {
  return getHouseholdSettingValue(key);
}

export function generateDiagnostics(): DiagnosticsReport {
  const peopleRows = db.select().from(people).where(isNull(people.deletedAt)).all() as PersonRow[];
  const endpointCount = db.select({ id: hubEndpoints.id }).from(hubEndpoints).all().length;
  const issueRows = db.select().from(issues).all();
  const packageRows = db.select().from(packageStatus).all();

  return {
    generatedAt: new Date().toISOString(),
    schemaVersion: CURRENT_SCHEMA_VERSION,
    hub: { instanceId: getHubInstanceId() },
    people: peopleRows.map((p) => ({ id: p.id, role: p.role, enabled: p.enabled, source: p.source, createdAt: p.createdAt })),
    endpointCount,
    issues: issueRows.map((i) => ({ source: i.source, key: i.key, severity: i.severity, createdAt: i.createdAt, resolvedAt: i.resolvedAt })),
    packages: packageRows.map((p) => ({ packageId: p.packageId, status: p.status, smokeOk: p.smokeOk })),
    settings: redactedHouseholdSettings(),
    storage: storageSummary(),
  };
}
