// GPU-01: a pre-household validation bench. It never starts an engine,
// opens the household database, or sends family data.
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { performance } from "node:perf_hooks";
import { readEngineIdentity, formatEngineIdentity } from "@/lib/engineIdentity";
import { readTextLines } from "@maipai/spec/streaming/ts/lineReader.js";

export interface Sample { tps: number; atSeconds: number; }
export interface ThroughputRow { concurrency: number; streamTps: number; aggregateTps: number; firstTokenP50Ms: number; firstTokenP95Ms: number; }
export function percentile(values: number[], p: number): number { if (!values.length) return 0; const sorted = [...values].sort((a, b) => a - b); return sorted[Math.min(sorted.length - 1, Math.ceil((p / 100) * sorted.length) - 1)]!; }
export function promptForContext(contextSize: number): string { const target = Math.max(256, Math.floor(contextSize * 0.9)); const paragraph = "Alfred, Juniper, Pippa, Clover, Rover, and Sprout are roster names in an invented household used only for engine validation. "; return Array(Math.ceil(target / paragraph.length)).fill(paragraph).join("").slice(0, target); }
export function throttleFindings(samples: Sample[], baselineSeconds = 120): Sample[] { const baseline = samples.filter((s) => s.atSeconds <= baselineSeconds).map((s) => s.tps); if (!baseline.length) return []; const mean = baseline.reduce((a, b) => a + b, 0) / baseline.length; return samples.filter((s) => s.atSeconds > baselineSeconds && s.tps < mean * 0.7); }
export function verdict(fillOk: boolean, rows: ThroughputRow[], findings: Sample[], minTps = 20): "pass" | "fail" { return fillOk && (rows.find((r) => r.concurrency === 1)?.streamTps ?? 0) >= minTps && findings.length === 0 ? "pass" : "fail"; }

async function streamReply(url: string, prompt: string, maxTokens: number): Promise<{ tokens: number; firstTokenMs: number; totalMs: number }> {
  const start = performance.now(); const response = await fetch(`${url.replace(/\/$/, "")}/v1/chat/completions`, { method: "POST", headers: { "content-type": "application/json" }, signal: AbortSignal.timeout(180_000), body: JSON.stringify({ model: "chat", messages: [{ role: "user", content: prompt }], stream: true, max_tokens: maxTokens, chat_template_kwargs: { enable_thinking: false } }) });
  if (!response.ok || !response.body) throw new Error(`engine answered ${response.status}`); let firstTokenMs: number | undefined; let tokens = 0;
  for await (const raw of readTextLines(response.body.getReader())) { const line = raw.trim(); if (!line.startsWith("data:") || line.slice(5).trim() === "[DONE]") continue; try { const chunk = JSON.parse(line.slice(5).trim()) as { choices?: Array<{ delta?: { content?: string } }>; usage?: { completion_tokens?: number } }; const text = chunk.choices?.[0]?.delta?.content; if (text && firstTokenMs === undefined) firstTokenMs = performance.now() - start; if (typeof chunk.usage?.completion_tokens === "number") tokens = chunk.usage.completion_tokens; else if (text) tokens += Math.max(1, text.trim().split(/\s+/).length); } catch { /* skip malformed frames */ } }
  if (firstTokenMs === undefined) throw new Error("the engine finished without a reply"); return { tokens, firstTokenMs, totalMs: performance.now() - start };
}
async function throughput(url: string, concurrency: number): Promise<ThroughputRow> { const started = performance.now(); const results: Awaited<ReturnType<typeof streamReply>>[] = []; for (let offset = 0; offset < 20; offset += concurrency) { results.push(...await Promise.all(Array.from({ length: Math.min(concurrency, 20 - offset) }, (_, i) => streamReply(url, `GPU validation synthetic request ${offset + i}: ${promptForContext(512)}`, 256)))); } const elapsed = (performance.now() - started) / 1000; const totalTokens = results.reduce((sum, r) => sum + r.tokens, 0); return { concurrency, streamTps: totalTokens / elapsed / concurrency, aggregateTps: totalTokens / elapsed, firstTokenP50Ms: percentile(results.map((r) => r.firstTokenMs), 50), firstTokenP95Ms: percentile(results.map((r) => r.firstTokenMs), 95) }; }

async function main(): Promise<void> { const url = process.env.MAIPAI_LLAMA_SERVER_URL; if (!url) { console.error("MAIPAI_LLAMA_SERVER_URL is required"); process.exitCode = 1; return; } const quick = process.argv.includes("--quick"); const minTps = Number(process.argv.find((a) => a.startsWith("--min-tps="))?.slice(10) ?? 20); const soakMinutes = Number(process.argv.find((a) => a.startsWith("--soak-minutes="))?.slice(15) ?? 20); const dataDir = mkdtempSync(`${tmpdir()}/maipai-gpu-validate-`); process.env.MAIPAI_DATA_DIR = dataDir; try { const identity = await readEngineIdentity(url); const propsResponse = await fetch(`${url.replace(/\/$/, "")}/props`, { signal: AbortSignal.timeout(5_000) }); const body = await propsResponse.json() as { context_size?: unknown; n_ctx?: unknown }; const contextSize = Number(body.context_size ?? body.n_ctx); if (!Number.isFinite(contextSize)) throw new Error("/props did not report a context size"); console.log("| phase | result |"); console.log("|---|---|"); console.log(`| identity | ${formatEngineIdentity(identity)}; context ${contextSize} |`); let fillOk = false; try { await streamReply(url, promptForContext(contextSize), 64); fillOk = true; console.log("| fill | pass |"); } catch (error) { console.log(`| fill | fail: ${error instanceof Error ? error.message : String(error)} |`); } const rows: ThroughputRow[] = []; for (const concurrency of [1, 2, 4]) { const row = await throughput(url, concurrency); rows.push(row); console.log(`| throughput/${concurrency} | stream ${row.streamTps.toFixed(2)} tps; aggregate ${row.aggregateTps.toFixed(2)} tps; first token p50 ${row.firstTokenP50Ms.toFixed(0)} ms p95 ${row.firstTokenP95Ms.toFixed(0)} ms |`); } const samples: Sample[] = []; if (!quick) { const end = Date.now() + soakMinutes * 60_000; const started = Date.now(); while (Date.now() < end) { const batch = await throughput(url, 2); samples.push({ atSeconds: (Date.now() - started) / 1000, tps: batch.streamTps }); console.log(`| soak | ${samples.at(-1)!.atSeconds.toFixed(0)} s; ${batch.streamTps.toFixed(2)} tps |`); } } const findings = throttleFindings(samples); const result = { identity: { build: identity.build, model: identity.model, contextSize }, fillOk, throughput: rows, soak: { minutes: soakMinutes, samples, findings }, verdict: verdict(fillOk, rows, findings, minTps) }; console.log(`| verdict | ${result.verdict} |`); console.log(JSON.stringify(result)); } finally { rmSync(dataDir, { recursive: true, force: true }); } }
if (import.meta.main) await main();
