export const TTS_PROOF_LINES: string[] = [
  "Good morning, kettle is ready.",
  "Please leave that window open.",
  "The blue basket is nearby.",
  "A quiet room helps everyone.",
  "The garden looks bright today.",
  "We have four clean cups.",
  "The small clock needs batteries.",
  "Could you read this note aloud?",
  "The train arrives at eight tonight.",
  "Please place the book beside it.",
  "A gentle breeze moved the curtains while the sunlight crossed the floor.",
  "On April 12, the community garden will open for its spring morning gathering.",
  "Would you bring the blue folder, two pencils, and a glass of water?",
  "The recipe calls for oats, apples, cinnamon, and a little maple syrup.",
  "At 6:30, the small library closes, and the lights in the front room dim.",
  "Could you explain why the moon appears to change shape during the month?",
  "The paper map shows three paths, a bridge, and a bench beside the pond.",
  "A warm loaf cooled on the rack while the afternoon rain tapped against the windows.",
  "The number 248 appears on the label, beneath a row of small green squares.",
  "Please set out four plates, six napkins, and a pitcher before the guests arrive.",
  "Before the morning walk, the hikers checked their water and packed fruit for the trail, then folded a light jacket into each bag and reviewed the route together.",
  "The town clock struck seven as steady rain softened the sounds from the street below, while a small lamp glowed beside the window and warmed the room.",
  "In the science room, a glass jar held warm water, a spoon, and smooth stones from the shore, ready for a simple experiment about heat and floating.",
  "A short note on the kitchen board listed bread, pears, rice, tea, and a bunch of parsley, with a reminder to check the pantry before shopping.",
  "When the last page turned, the reading group shared a favorite detail and returned every book to its shelf, leaving the room tidy for the next gathering.",
  "At 9:45 on October 3, the neighborhood hall will host a quiet repair workshop for lamps, radios, and clocks, with tools provided at each wide table.",
  "Could you tell whether the second path reaches the pond before the old stone bridge at the edge of the park, then returns past the community garden?",
  "The weather report expects clear skies, cool air, and a light breeze through Saturday afternoon, so the open field should stay comfortable for a long walk.",
  "A careful list helps the kitchen team prepare soup, warm rolls, sliced fruit, and enough cups for everyone, while keeping the serving counter clear and orderly.",
  "The train crossed a wide river, passed quiet farms, and reached the station before the evening lights came on, carrying travelers toward the town square.",
];
