import { getIcon } from "@/kit/icons";
import { Progress as ProgressBar } from "@/kit/ui/progress";

interface ProgressProps {
  mode: "spinner" | "determinate";
  value?: number;
  label?: string;
}

// v0 only ever renders `spinner` (Chat has nothing determinate to show
// yet); `determinate` is typed to match spec/ui/schema.json's mode enum
// but has no real caller tonight, same "typed, not yet implemented"
// posture as llm.ts's role list. The determinate bar itself is
// `kit/ui/progress.tsx` (Radix's Progress, generated by shadcn), not a
// hand-rolled div; there is no library "spinner" component, so the
// spinner mode stays the kit's own icon-plus-`animate-spin` idiom, the
// same one `kit/ui/sonner.tsx`'s loading toast icon already uses.
export function Progress({ mode, value, label }: ProgressProps) {
  const Spinner = getIcon("loader");
  if (mode === "determinate") {
    const pct = Math.max(0, Math.min(100, value ?? 0));
    return <ProgressBar value={pct} aria-label={label} />;
  }
  return (
    <div className="flex items-center gap-2 text-base text-muted-foreground" role="status">
      <Spinner className="h-4 w-4 animate-spin" aria-hidden />
      {label ? <span>{label}</span> : null}
    </div>
  );
}
