import {
  MessageCircle,
  Send,
  LogOut,
  User,
  Users,
  Loader2,
  HelpCircle,
  Settings,
  Brain,
  Ear,
  Eye,
  Speech,
  Archive,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  AlertTriangle,
  Volume2,
  VolumeX,
  ShieldCheck,
  Lock,
  X,
  Bell,
  Inbox,
  MoreHorizontal,
  PanelLeft,
  Home,
  Pin,
  PinOff,
  Search,
  Sparkles,
  Mic,
  LayoutGrid,
  Grid2x2,
  History,
  Activity,
  Info,
  SlidersHorizontal,
  type LucideIcon,
} from "lucide-react";

// docs/UI.md: "Icons: lucide only, by name... no other icon set." The kit
// owns the name -> component registry so app code (and, later, JSON page
// data) references an icon by its lucide kebab-case name and never
// imports lucide-react directly. Grows as pages need more; nothing here
// is speculative.
const REGISTRY: Record<string, LucideIcon> = {
  ear: Ear,
  eye: Eye,
  speech: Speech,
  "message-circle": MessageCircle,
  send: Send,
  "log-out": LogOut,
  user: User,
  users: Users,
  loader: Loader2,
  settings: Settings,
  brain: Brain,
  archive: Archive,
  check: CheckCircle2,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "alert-triangle": AlertTriangle,
  "volume-2": Volume2,
  "volume-x": VolumeX,
  "shield-check": ShieldCheck,
  lock: Lock,
  x: X,
  bell: Bell,
  inbox: Inbox,
  "more-horizontal": MoreHorizontal,
  "panel-left": PanelLeft,
  home: Home,
  pin: Pin,
  "pin-off": PinOff,
  search: Search,
  sparkles: Sparkles,
  mic: Mic,
  "layout-grid": LayoutGrid,
  "grid-2x2": Grid2x2,
  history: History,
  activity: Activity,
  info: Info,
  "sliders-horizontal": SlidersHorizontal,
};

export function getIcon(name: string): LucideIcon {
  return REGISTRY[name] ?? HelpCircle;
}
