// ACT-02: the 500-turn human review sheet for the 4B-labeled act/stance
// corpus (docs/dev.md section 12: "a 500-turn sample of those labels
// reviewed by a person and the agreement recorded"). Same shape as lane
// 13's phenomenon review sheet (scripts/bench/datasets/mine.ts's
// renderReviewSheet(), git-ignored under data-scratch/eval/): a person
// marks each row keep/skip and the agreement rate becomes the real
// number, never the 4B agreeing with itself. Per the coordinator's
// clearance for this run (2026-09-14): the stance head's acceptance
// number WAITS for this review; this file only produces the sheet.
import { seededShuffle } from "../bench/datasets/sample";
import type { LabeledTurn } from "./labelActStance";

const REVIEW_SEED = 20260914;
export const REVIEW_SAMPLE_SIZE = 500;

function checkbox(): string {
  return "- [ ] agree   - [ ] disagree - act   - [ ] disagree - stance   - [ ] disagree - both   - note: ___________________________";
}

export function sampleForReview(corpus: readonly LabeledTurn[], sampleSize: number = REVIEW_SAMPLE_SIZE): LabeledTurn[] {
  return seededShuffle(corpus, REVIEW_SEED).slice(0, Math.min(sampleSize, corpus.length));
}

export function renderReviewSheet(sample: readonly LabeledTurn[]): string {
  const lines: string[] = [
    "# ACT-02 4B label review sheet",
    "",
    `Generated by \`bun run backend/scripts/train/turn-signal-heads.ts\`. ${sample.length} turns, seed-`,
    "sampled from the 4B-labeled act/stance training corpus (Taskmaster-1,",
    "CCPE-M, the bench fixture, synthetic roster dialogues). Mark each row",
    "agree (the act and stance are both right), or disagree on the act, the",
    "stance, or both, with a one-line note when a disagreement isn't",
    "obvious from the label alone. This file is git-ignored: never commit",
    "dataset text. The stance head's validated precision-per-class number",
    "in the training report is this sheet's agreement rate, not a number",
    "computed from the 4B agreeing with itself.",
    "",
  ];
  sample.forEach((row, i) => {
    lines.push(`## ${i + 1}. \`${row.id}\``, "", `> ${row.text}`, "", `4B label: act = **${row.act}**, stance = **${row.stance}**`, "", checkbox(), "");
  });
  return lines.join("\n");
}
