"use client";

// Generated by the assistant-ui registry (frontend/eslint.config.js has
// this directory's own exemption comment); one exception to "kit doesn't
// import from apps": chatActionBar.tsx below is chat-specific, not a
// generic primitive, and this file - unlike Button or Card - is only
// ever mounted by ChatPage.tsx. There is no real second consumer this
// could leak into.

import {
  ComposerAttachments,
  UserMessageAttachments,
} from "@/kit/assistant-ui/attachment.aui";
import { File } from "@/kit/assistant-ui/file";
import { ThreadFollowupSuggestions } from "@/kit/assistant-ui/follow-up-suggestions.aui";
import { Image } from "@/kit/assistant-ui/image";
import { MarkdownText } from "@/kit/assistant-ui/markdown-text";
import {
  Reasoning,
  ReasoningContent,
  ReasoningRoot,
  ReasoningText,
  ReasoningTrigger,
} from "@/kit/assistant-ui/reasoning.aui";
import { ToolFallback } from "@/kit/assistant-ui/tool-fallback.aui";
import {
  ToolGroupContent,
  ToolGroupRoot,
  ToolGroupTrigger,
} from "@/kit/assistant-ui/tool-group.aui";
import { TooltipIconButton } from "@/kit/assistant-ui/tooltip-icon-button";
import { ChatFeedbackOpenContext, FeedbackButtons, ForgetThisMenuItem, ListenButton, RememberThisButton, RememberThisMenuItem } from "@/apps/chat/chatActionBar";
import { setPendingContinuation } from "@/apps/chat/chatContinue";
import { setPendingSupersedes } from "@/apps/chat/chatEditSupersedes";
import { MemoryUpdatedChip } from "@/apps/chat/chatMemoryChip";
import { ChatSourceCaption } from "@/apps/chat/chatSourceCaption";
import { ChatMedia, markCitations, type TurnWithMedia, type TurnWithSources } from "@/apps/chat/chatCitations";
import { useTurnActivity } from "@/apps/chat/chatTurnActivity";
import { createCitationComponents } from "@/apps/chat/chatCitationLink";
import { SourcesCard } from "@/apps/chat/chatSourcesCard";
import { ChatDocumentHandle } from "@/apps/chat/chatDocumentPane";
import { ChatTurnStats } from "@/apps/chat/chatTurnStats";
import { messageText } from "@/apps/chat/chatMessageText";
import { DayBoundaryProvider, DayDivider, MessageTimestamp } from "@/apps/chat/chatDayDivider";
import { api } from "@/lib/api";
import { Button } from "@maipai/ui/src/ui/button";
import { Skeleton } from "@maipai/ui/src/ui/skeleton";
import { cn } from "@maipai/ui/src/utils";
import {
  ActionBarMorePrimitive,
  ActionBarPrimitive,
  AuiIf,
  type AssistantState,
  BranchPickerPrimitive,
  ComposerPrimitive,
  ErrorPrimitive,
  groupPartByType,
  MessagePrimitive,
  SuggestionPrimitive,
  ThreadPrimitive,
  type FileMessagePartComponent,
  type ImageMessagePartComponent,
  type ToolCallMessagePartComponent,
  useAuiState,
} from "@assistant-ui/react";
import {
  ArrowDownIcon,
  ArrowUpIcon,
  CheckIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  CopyIcon,
  DownloadIcon,
  MicIcon,
  MoreHorizontalIcon,
  PencilIcon,
  RefreshCwIcon,
  SquareIcon,
} from "lucide-react";
import {
  createContext,
  useContext,
  useMemo,
  useEffect,
  useRef,
  type ComponentType,
  type FC,
  type PropsWithChildren,
  type ReactNode,
} from "react";

export type ThreadGroupPart = MessagePrimitive.GroupedParts.GroupPart;

/**
 * Optional component overrides for the thread. `AssistantMessage` and
 * `Welcome` replace whole sections; the remaining slots override how the
 * assistant message renders tool calls and part groups. Tool UIs registered
 * by name (toolkit `render`, `useAssistantDataUI`) take precedence over
 * `ToolFallback`.
 */
export type ThreadComponents = {
  AssistantMessage?: ComponentType | undefined;
  Welcome?: ComponentType | undefined;
  ToolFallback?: ToolCallMessagePartComponent | undefined;
  ToolGroup?:
    | ComponentType<PropsWithChildren<{ group: ThreadGroupPart }>>
    | undefined;
  ReasoningGroup?:
    | ComponentType<PropsWithChildren<{ group: ThreadGroupPart }>>
    | undefined;
};

export type ThreadProps = {
  components?: ThreadComponents | undefined;
  autoFocus?: boolean | undefined;
  /** Extra controls rendered directly above the composer (not the page
   * header) - per-turn behavior toggles (a wake-word listener, "think
   * longer") read as odd floating above the whole message history, but
   * make sense sitting right next to the thing they actually affect: the
   * next message a person sends (Jesse, 2026-09-06: "its placement /
   * location is also odd"). */
  composerToolbar?: ReactNode | undefined;
  /** When set, the composer's input and send control are disabled (the
   * model isn't ready to receive a turn) and this explains why - e.g.
   * "MaiPai's AI is starting up." (useEngineHealth.ts's `brainBlockReason`). */
  composerDisabled?: boolean | undefined;
  composerDisabledReason?: string | undefined;
};

const EMPTY_COMPONENTS: ThreadComponents = {};

const ThreadComponentsContext =
  createContext<ThreadComponents>(EMPTY_COMPONENTS);

// Startup exposes a loading placeholder thread; treat it as a new chat so
// the composer mounts centered. Loads after startup keep the docked layout.
const isNewChatView = (s: AssistantState) =>
  s.thread.messages.length === 0 &&
  (!s.thread.isLoading || s.threads.isLoading);

// A switched thread that is still fetching its history: skeleton, not welcome.
const isHistoryLoadingView = (s: AssistantState) =>
  s.thread.messages.length === 0 &&
  s.thread.isLoading &&
  !s.thread.isDisabled &&
  !s.threads.isLoading;

const ThreadHistorySkeleton: FC = () => (
  <div
    data-slot="aui_thread-history-skeleton"
    role="status"
    className="animate-in fade-in fill-mode-both flex flex-col gap-y-6 [animation-delay:150ms] [animation-duration:200ms]"
  >
    <span className="sr-only">Loading conversation</span>
    <Skeleton className="ml-auto h-9 w-2/5 rounded-xl motion-reduce:animate-none" />
    <div className="flex flex-col gap-y-2">
      <Skeleton className="h-4 w-11/12 motion-reduce:animate-none" />
      <Skeleton className="h-4 w-4/5 motion-reduce:animate-none" />
      <Skeleton className="h-4 w-3/5 motion-reduce:animate-none" />
    </div>
    <Skeleton className="ml-auto h-9 w-1/3 rounded-xl motion-reduce:animate-none" />
    <div className="flex flex-col gap-y-2">
      <Skeleton className="h-4 w-10/12 motion-reduce:animate-none" />
      <Skeleton className="h-4 w-2/3 motion-reduce:animate-none" />
    </div>
  </div>
);

export const Thread: FC<ThreadProps> = ({
  components = EMPTY_COMPONENTS,
  autoFocus = true,
  composerToolbar,
  composerDisabled,
  composerDisabledReason,
}) => {
  const isEmpty = useAuiState(isNewChatView);

  return (
    <ThreadComponentsContext.Provider value={components}>
      <ThreadRoot
        isEmpty={isEmpty}
        autoFocus={autoFocus}
        composerToolbar={composerToolbar}
        composerDisabled={composerDisabled}
        composerDisabledReason={composerDisabledReason}
      />
    </ThreadComponentsContext.Provider>
  );
};

const ThreadRoot: FC<{
  isEmpty: boolean;
  autoFocus: boolean;
  composerToolbar?: ReactNode;
  composerDisabled?: boolean;
  composerDisabledReason?: string;
}> = ({ isEmpty, autoFocus, composerToolbar, composerDisabled, composerDisabledReason }) => {
  const { Welcome = ThreadWelcome } = useContext(ThreadComponentsContext);
  const isHistoryLoading = useAuiState(isHistoryLoadingView);

  return (
    <ThreadPrimitive.Root
      className="aui-root aui-thread-root min-h-0 bg-background @container flex h-full flex-col"
      style={{
        ["--thread-max-width" as string]: "44rem",
        ["--composer-bg" as string]: "var(--color-card)",
        ["--composer-radius" as string]: "1.5rem",
        ["--composer-padding" as string]: "8px",
      }}
    >
      <ThreadPrimitive.Viewport
        turnAnchor="top"
        data-slot="aui_thread-viewport"
        className="relative flex min-h-0 flex-1 flex-col overflow-x-auto overflow-y-scroll scroll-smooth"
      >
        <div
          className={cn("mx-auto flex w-full max-w-(--thread-max-width) flex-1 flex-col px-4 pt-4", isEmpty && "sm:justify-center")}
        >
          {/* Desktop centers the greeting WITH the composer right underneath
              it as one group, Claude.ai/ChatGPT-style (`sm:` and up only) -
              centering belongs on this shared outer wrapper (so the footer
              below, a flow sibling, centers along with the greeting) rather
              than on the greeting's own inner wrapper alone: a `flex-1
              justify-center` on the inner wrapper only centers the greeting
              WITHIN its own box (which spans the full remaining height),
              leaving the footer pinned far below at the true bottom edge
              instead of sitting just under the greeting. On phone, that same
              centering left the composer floating mid-screen with a dead gap
              below it instead of sitting at the thumb-reachable bottom edge
              every other mobile chat surface uses (Jesse, 2026-09-07) - so
              this only applies at `sm:` and up. */}
          <div className="w-full flex flex-col items-center">
            <AuiIf condition={isNewChatView}>
              <Welcome />
            </AuiIf>
            <AuiIf condition={isHistoryLoadingView}>
              <ThreadHistorySkeleton />
            </AuiIf>
          </div>

          {/* `mt-auto` only once there's a real transcript: a real repro
              (headless Chromium against a throwaway seeded backend, since
              Chat needs a signed-in session and the live household's PIN is
              off-limits to type - 2026-09-07) screenshotted a 2-message
              conversation with the exchange stuck at the TOP of the screen
              and a ~280px dead gap before the composer, because the footer's
              own `mt-auto` (below) was doing the only bottom-pinning in the
              whole tree - it pushed itself down, not the messages. Giving
              the messages their own `mt-auto` instead pins THEM to sit right
              above the composer, the same "recent turns anchored to the
              composer, empty space floats to the top" every real chat
              surface uses. Empty:hidden means this is a no-op (0 height, no
              margin) in the empty-chat case, where the footer's own
              `mt-auto` below still does the work exactly as before. */}
          <div
            data-slot="aui_message-group"
            className={cn("mb-14 flex flex-col gap-y-6 empty:hidden", !isEmpty && "mt-auto")}
          >
            <DayBoundaryProvider>
              <ThreadPrimitive.Messages>
                {() => <ThreadMessage />}
              </ThreadPrimitive.Messages>
            </DayBoundaryProvider>
          </div>

          <ThreadPrimitive.ViewportFooter
            className={cn(
              "aui-thread-viewport-footer bg-background flex flex-col gap-4 overflow-visible pb-0 sticky bottom-0 rounded-t-(--composer-radius)",
              // getmaipai/home#75 (found live, 2026-09-13, via the WebKit
              // chat exercise - WebKit's click refuses to click through
              // something else, Chromium apparently doesn't, so only
              // WebKit ever surfaced this): `translate-y-9` below pushes
              // the footer 36px further down once a real transcript is
              // loaded, with nothing offsetting that against `PhoneNav`'s
              // own fixed bar at the true viewport bottom - measured live,
              // the composer's bottom edge (816px) sat 27px inside the
              // nav's top edge (789px), so a real phone tap on Send lands
              // on the nav instead. `max-sm:bottom-16` reuses the exact
              // clearance `Shell.tsx`'s own `pb-16 sm:pb-0` already
              // reserves for PhoneNav on ordinary page content (the one
              // existing definition of "PhoneNav's height" in this
              // codebase - a CSS custom property purely for this pairing
              // would be a second definition, not one), so the footer's
              // sticking point moves up by the same amount every other
              // phone surface already clears by. `sm:bottom-0` below
              // still wins at `sm:` and up, where PhoneNav is hidden.
              !isEmpty && "translate-y-9 max-sm:bottom-16",
              "sm:translate-y-0 sm:pb-6",
              // Below `sm`, an empty thread still pins the composer to the
              // bottom edge (`mt-auto`) - the mobile "thumb-reachable
              // bottom" design stands regardless of desktop centering. At
              // `sm:` and up, the outer wrapper's own `sm:justify-center`
              // (above) does the work of keeping the greeting and composer
              // together as one centered group instead - `mt-auto` here
              // would fight that by pinning the footer to the true bottom.
              isEmpty && "mt-auto sm:mt-0",
              isHistoryLoading && "mt-auto",
            )}
          >
            <ThreadScrollToBottom />
            <ThreadFollowupSuggestions />
            <Composer autoFocus={autoFocus} toolbar={composerToolbar} disabled={composerDisabled} disabledReason={composerDisabledReason} />
            <AuiIf condition={(s) => isNewChatView(s) && s.composer.isEmpty}>
              <ThreadSuggestions />
            </AuiIf>
          </ThreadPrimitive.ViewportFooter>
        </div>
      </ThreadPrimitive.Viewport>
    </ThreadPrimitive.Root>
  );
};

const ThreadMessage: FC = () => {
  const { AssistantMessage: AssistantMessageComponent = AssistantMessage } =
    useContext(ThreadComponentsContext);
  const role = useAuiState((s) => s.message.role);
  const isEditing = useAuiState((s) => s.message.composer.isEditing);

  if (isEditing) return <EditComposer />;
  return (
    <>
      <DayDivider />
      {role === "user" ? <UserMessage /> : <AssistantMessageComponent />}
    </>
  );
};

const ThreadScrollToBottom: FC = () => {
  const feedbackOpen = useContext(ChatFeedbackOpenContext);
  if (feedbackOpen) return null;
  return (
    <ThreadPrimitive.ScrollToBottom asChild>
      <TooltipIconButton
        tooltip="Scroll to bottom"
        variant="outline"
        className="aui-thread-scroll-to-bottom dark:border-border dark:bg-background dark:hover:bg-accent absolute -top-12 z-10 self-center rounded-full p-4 disabled:invisible"
      >
        <ArrowDownIcon />
      </TooltipIconButton>
    </ThreadPrimitive.ScrollToBottom>
  );
};

const ThreadWelcome: FC = () => {
  return (
    <div className="aui-thread-welcome-root mb-6 flex flex-col items-center px-4 text-center">
      <h1 className="aui-thread-welcome-message-inner fade-in slide-in-from-bottom-1 animate-in fill-mode-both text-2xl font-medium tracking-tight duration-200">
        How can I help you today?
      </h1>
    </div>
  );
};

const ThreadSuggestions: FC = () => {
  return (
    <div className="aui-thread-welcome-suggestions flex w-full flex-wrap items-center justify-center gap-2 px-4">
      <ThreadPrimitive.Suggestions>
        {() => <ThreadSuggestionItem />}
      </ThreadPrimitive.Suggestions>
    </div>
  );
};

const ThreadSuggestionItem: FC = () => {
  return (
    <div className="aui-thread-welcome-suggestion-display fade-in slide-in-from-bottom-2 animate-in fill-mode-both duration-200">
      <SuggestionPrimitive.Trigger send asChild>
        <Button
          variant="ghost"
          className="aui-thread-welcome-suggestion text-foreground hover:bg-muted border-border/60 h-auto gap-1.5 rounded-full border px-3.5 py-1.5 text-sm font-normal whitespace-nowrap transition-colors"
        >
          <SuggestionPrimitive.Title className="aui-thread-welcome-suggestion-text-1" />
          <SuggestionPrimitive.Description className="aui-thread-welcome-suggestion-text-2 empty:hidden" />
        </Button>
      </SuggestionPrimitive.Trigger>
    </div>
  );
};

const Composer: FC<{ autoFocus: boolean; toolbar?: ReactNode; disabled?: boolean; disabledReason?: string }> = ({ autoFocus, toolbar, disabled, disabledReason }) => {
  return (
    <ComposerPrimitive.Root className="aui-composer-root relative flex w-full flex-col">
      <ComposerPrimitive.AttachmentDropzone asChild>
        <div
          data-slot="aui_composer-shell"
          className="border-border/60 data-[dragging=true]:border-ring focus-within:border-border dark:border-muted-foreground/15 dark:focus-within:border-muted-foreground/30 flex w-full cursor-text items-end gap-1 rounded-(--composer-radius) border bg-(--composer-bg) p-(--composer-padding) transition-[border-color] data-[dragging=true]:border-dashed data-[dragging=true]:bg-[color-mix(in_oklab,var(--color-accent)_50%,var(--color-background))]"
        >
          <ComposerAttachments />
          {toolbar ? <div className="flex shrink-0 items-center gap-1">{toolbar}</div> : null}
          <ComposerPrimitive.Input
            placeholder={disabled ? (disabledReason ?? "MaiPai's AI isn't ready yet.") : "Send a message..."}
            disabled={disabled}
            // min-h-12 (48px), not min-h-9: the touch-target floor
            // (docs/UI.md, BACKLOG.md lane 8 item 1, 2026-09-13) - the
            // composer's own text field, a real tap target every message
            // starts with, measured under 48px tall by the live check.
            className="aui-composer-input caret-primary placeholder:text-muted-foreground/60 max-h-48 min-h-12 min-w-0 flex-1 resize-none bg-transparent px-1 py-3 text-base leading-6 outline-none disabled:cursor-not-allowed"
            rows={1}
            autoFocus={autoFocus}
            enterKeyHint="send"
            aria-label="Message input"
          />
          <ComposerAction disabled={disabled} disabledReason={disabledReason} />
        </div>
      </ComposerPrimitive.AttachmentDropzone>
    </ComposerPrimitive.Root>
  );
};

const ComposerAction: FC<{ disabled?: boolean; disabledReason?: string }> = ({ disabled, disabledReason }) => {
  return (
    <div className="aui-composer-action-wrapper relative flex shrink-0 items-center">
      <div className="flex items-center gap-1.5">
        <AuiIf condition={(s) => s.thread.capabilities.dictation}>
          <AuiIf condition={(s) => s.composer.dictation == null}>
            <ComposerPrimitive.Dictate asChild>
              <TooltipIconButton
                tooltip="Voice input"
                side="bottom"
                type="button"
                variant="ghost"
                size="icon"
                className="aui-composer-dictate text-muted-foreground hover:text-foreground size-9 rounded-full relative before:absolute before:-inset-1.5 before:content-['']"
                aria-label="Start voice input"
              >
                <MicIcon className="aui-composer-dictate-icon size-4" />
              </TooltipIconButton>
            </ComposerPrimitive.Dictate>
          </AuiIf>
          <AuiIf condition={(s) => s.composer.dictation != null}>
            <ComposerPrimitive.StopDictation asChild>
              <TooltipIconButton
                tooltip="Stop dictation"
                side="bottom"
                type="button"
                variant="ghost"
                size="icon"
                className="aui-composer-stop-dictation text-destructive size-9 rounded-full relative before:absolute before:-inset-1.5 before:content-['']"
                aria-label="Stop voice input"
              >
                <SquareIcon className="aui-composer-stop-dictation-icon size-3.5 animate-pulse fill-current" />
              </TooltipIconButton>
            </ComposerPrimitive.StopDictation>
          </AuiIf>
        </AuiIf>
        {disabled ? (
          // The model isn't ready for a turn (useEngineHealth.ts) - a
          // plain disabled button, not the AuiIf/isRunning switch below,
          // since assistant-ui's own send-disabled logic (empty composer,
          // thread already running) knows nothing about backend
          // readiness and would otherwise leave this enabled the moment
          // there's text to send.
          <TooltipIconButton
            tooltip={disabledReason ?? "MaiPai's AI isn't ready yet."}
            side="bottom"
            type="button"
            variant="default"
            size="icon"
            disabled
            className="aui-composer-send size-9 rounded-full relative before:absolute before:-inset-1.5 before:content-['']"
            aria-label="Send message"
          >
            <ArrowUpIcon className="aui-composer-send-icon size-4" />
          </TooltipIconButton>
        ) : (
          <>
            <AuiIf condition={(s) => !s.thread.isRunning}>
              <ComposerPrimitive.Send asChild>
                <TooltipIconButton
                  tooltip="Send message"
                  side="bottom"
                  type="button"
                  variant="default"
                  size="icon"
                  className="aui-composer-send size-9 rounded-full relative before:absolute before:-inset-1.5 before:content-['']"
                  aria-label="Send message"
                >
                  <ArrowUpIcon className="aui-composer-send-icon size-4" />
                </TooltipIconButton>
              </ComposerPrimitive.Send>
            </AuiIf>
            <AuiIf condition={(s) => s.thread.isRunning}>
              <ComposerPrimitive.Cancel asChild>
                <Button
                  type="button"
                  variant="default"
                  size="icon"
                  className="aui-composer-cancel size-9 rounded-full relative before:absolute before:-inset-1.5 before:content-['']"
                  aria-label="Stop generating"
                >
                  <SquareIcon className="aui-composer-cancel-icon size-3.5 fill-current" />
                </Button>
              </ComposerPrimitive.Cancel>
            </AuiIf>
          </>
        )}
      </div>
    </div>
  );
};

const MessageError: FC = () => {
  return (
    <MessagePrimitive.Error>
      <ErrorPrimitive.Root className="aui-message-error-root border-destructive bg-destructive/10 text-destructive dark:bg-destructive/5 mt-2 rounded-md border p-3 text-sm dark:text-red-200">
        <ErrorPrimitive.Message className="aui-message-error-message line-clamp-2" />
      </ErrorPrimitive.Root>
    </MessagePrimitive.Error>
  );
};

const AssistantMessage: FC = () => {
  const {
    ToolFallback: ToolFallbackComponent = ToolFallback,
    ToolGroup,
    ReasoningGroup,
  } = useContext(ThreadComponentsContext);

  const ACTION_BAR_PT = "pt-1.5";
  // Keep the action bar inside the contained root's paint box, then cancel its reserved space in flow.
  const ACTION_BAR_HEIGHT = `min-h-7.5 ${ACTION_BAR_PT}`;
  // docs/plans/session-b-ui.md step 4: "aria-live on the streaming
  // message" - only while THIS message is running, so a screen reader
  // doesn't announce every settled message's content on every DOM change
  // elsewhere in the thread.
  const running = useAuiState((s) => s.message.status?.type === "running");
  // Lane 10 item 1: read the same "custom" metadata bag ChatSourceCaption/
  // MemoryUpdatedChip already do, tolerant of `sources` being absent (both
  // adapters carry it forward when present; nothing here requires it).
  const sources = useAuiState((s) => (s.message.metadata?.custom as TurnWithSources | undefined)?.sources);
  const mediaMetadata = useAuiState((s) => s.message.metadata?.custom as TurnWithMedia | undefined);
  const citationComponents = useMemo(() => createCitationComponents(sources), [sources]);
  const markCitationsIn = useMemo(() => (text: string) => markCitations(text, sources), [sources]);
  // Lane 11 item 1: the same existing pending affordance below (the
  // pulsing dot, "indicator" part) just swaps its static "Thinking…" for
  // this transient text when CHAT-16's status/spoken_cue has one -
  // chatTurnActivity.ts's own header on why this is the one field both
  // event kinds drive.
  const activity = useTurnActivity();

  return (
    <MessagePrimitive.Root
      data-slot="aui_assistant-message-root"
      data-role="assistant"
      className="fade-in slide-in-from-bottom-1 animate-in relative -mb-7.5 pb-7.5 duration-150 [contain-intrinsic-size:auto_200px] [content-visibility:auto]"
    >
      <div
        data-slot="aui_assistant-message-content"
        className="text-foreground px-2 leading-relaxed wrap-break-word"
        aria-live={running ? "polite" : "off"}
        aria-atomic="false"
      >
        <MessagePrimitive.GroupedParts
          groupBy={groupPartByType({
            reasoning: ["group-chainOfThought", "group-reasoning"],
            "tool-call": ["group-chainOfThought", "group-tool"],
            "standalone-tool-call": [],
          })}
        >
          {({ part, children }) => {
            switch (part.type) {
              case "group-chainOfThought":
                return <div data-slot="aui_chain-of-thought">{children}</div>;
              case "group-tool":
                if (ToolGroup) {
                  return <ToolGroup group={part}>{children}</ToolGroup>;
                }
                return (
                  <ToolGroupRoot variant="ghost">
                    <ToolGroupTrigger
                      count={part.indices.length}
                      active={part.status.type === "running"}
                    />
                    <ToolGroupContent>{children}</ToolGroupContent>
                  </ToolGroupRoot>
                );
              case "group-reasoning": {
                if (ReasoningGroup) {
                  return (
                    <ReasoningGroup group={part}>{children}</ReasoningGroup>
                  );
                }
                const running = part.status.type === "running";
                return (
                  <ReasoningRoot streaming={running}>
                    <ReasoningTrigger active={running} />
                    <ReasoningContent aria-busy={running}>
                      <ReasoningText>{children}</ReasoningText>
                    </ReasoningContent>
                  </ReasoningRoot>
                );
              }
              case "text":
                return <MarkdownText components={citationComponents} preprocess={markCitationsIn} />;
              case "reasoning":
                return <Reasoning {...part} />;
              case "tool-call":
                return part.toolUI ?? <ToolFallbackComponent {...part} />;
              case "data":
                return part.dataRendererUI;
              case "file":
                return (
                  <div data-slot="aui_assistant-message-file" className="py-1">
                    <File {...part} />
                  </div>
                );
              case "image":
                return (
                  <div data-slot="aui_assistant-message-image" className="py-1">
                    <Image {...part} />
                  </div>
                );
              case "indicator":
                return (
                  <span
                    data-slot="aui_assistant-message-indicator"
                    className="inline-flex items-center gap-2 text-sm text-muted-foreground motion-safe:animate-pulse"
                    aria-label="Assistant is working"
                  >
                    <><span aria-hidden="true">●</span> {activity ?? "Thinking…"}</>
                  </span>
                );
              default:
                return null;
            }
          }}
        </MessagePrimitive.GroupedParts>
        <MessageError />
        <ChatSourceCaption />
        <ChatTurnStats />
        <ChatMedia media={mediaMetadata?.media} media_items={mediaMetadata?.media_items} sources={sources} />
        {!running && <SourcesCard sources={sources} />}
        <MemoryUpdatedChip />
      </div>

      <div
        data-slot="aui_assistant-message-footer"
        className={cn("ms-2 flex items-center", ACTION_BAR_HEIGHT)}
      >
        <BranchPicker />
        <AssistantActionBar />
        <ChatDocumentHandle />
        <MessageTimestamp />
      </div>
    </MessagePrimitive.Root>
  );
};

// getmaipai/home#82: shared by AssistantActionBar and UserActionBar - a
// household member's own messages get the identical Copy affordance
// (icon, tooltip, isCopied swap) replies already had, `className` only
// place they differ (UserActionBar's own `aui-user-action-copy` hook for
// its bar's layout).
const MessageCopyButton: FC<{ className?: string }> = ({ className }) => (
  <ActionBarPrimitive.Copy asChild>
    <TooltipIconButton tooltip="Copy" className={className}>
      <AuiIf condition={(s) => s.message.isCopied}>
        <CheckIcon className="animate-in zoom-in-50 fade-in duration-200 ease-out" />
      </AuiIf>
      <AuiIf condition={(s) => !s.message.isCopied}>
        <CopyIcon className="animate-in zoom-in-75 fade-in duration-150" />
      </AuiIf>
    </TooltipIconButton>
  </ActionBarPrimitive.Copy>
);

const AssistantActionBar: FC = () => {
  return (
    <ActionBarPrimitive.Root
      hideWhenRunning
      autohide="not-last"
      className="aui-assistant-action-bar-root text-muted-foreground animate-in fade-in col-start-3 row-start-2 -ms-1 flex gap-1 duration-200"
    >
      <MessageCopyButton />
      <ContinueButton />
      <ActionBarPrimitive.Reload asChild>
        <TooltipIconButton tooltip="Refresh">
          <RefreshCwIcon />
        </TooltipIconButton>
      </ActionBarPrimitive.Reload>
      <ListenButton />
      <FeedbackButtons />
      <ActionBarMorePrimitive.Root>
        <ActionBarMorePrimitive.Trigger asChild>
          <TooltipIconButton
            tooltip="More"
            className="data-[state=open]:bg-accent"
          >
            <MoreHorizontalIcon />
          </TooltipIconButton>
        </ActionBarMorePrimitive.Trigger>
        <ActionBarMorePrimitive.Content
          side="bottom"
          align="start"
          sideOffset={6}
          className="aui-action-bar-more-content bg-popover text-popover-foreground data-[state=open]:fade-in-0 data-[state=open]:zoom-in-95 data-[state=open]:animate-in data-[state=closed]:fade-out-0 data-[state=closed]:zoom-out-95 data-[state=closed]:animate-out data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2 z-50 min-w-[8rem] overflow-hidden rounded-xl border p-1.5"
        >
          <ActionBarPrimitive.ExportMarkdown asChild>
            <ActionBarMorePrimitive.Item className="aui-action-bar-more-item hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground flex cursor-pointer items-center gap-2 rounded-lg px-2.5 py-1.5 text-sm outline-none select-none">
              <DownloadIcon className="size-4" />
              Export as Markdown
            </ActionBarMorePrimitive.Item>
          </ActionBarPrimitive.ExportMarkdown>
          <RememberThisMenuItem />
          <ForgetThisMenuItem />
        </ActionBarMorePrimitive.Content>
      </ActionBarMorePrimitive.Root>
    </ActionBarPrimitive.Root>
  );
};

/** CHAT-PARITY-04: assistant-ui's reload is the branch primitive we need,
 * while this click supplies the stopped text the adapter cannot recover
 * from its normal message list. It is deliberately available for every
 * incomplete reason; the engine reruns its safety and output boundaries
 * before delivering the continuation. */
const ContinueButton: FC = () => {
  const message = useAuiState((s) => s.message);
  if (message.role !== "assistant" || message.status.type !== "incomplete") return null;
  const assistantText = messageText(message);
  if (!assistantText.trim()) return null;
  const turnId = typeof message.metadata?.custom?.turnId === "string" ? message.metadata.custom.turnId : undefined;
  const handleContinue = () => setPendingContinuation({ assistantText, ...(turnId ? { fromTurnId: turnId } : {}) });
  return (
    <ActionBarPrimitive.Reload asChild onClick={handleContinue}>
      <TooltipIconButton tooltip="Continue" aria-label="Continue">
        <ArrowDownIcon />
      </TooltipIconButton>
    </ActionBarPrimitive.Reload>
  );
};

const UserFilePart: FileMessagePartComponent = (part) => (
  <div data-slot="aui_user-message-file" className="py-1">
    <File {...part} />
  </div>
);

const UserImagePart: ImageMessagePartComponent = (part) => (
  <div data-slot="aui_user-message-image" className="py-1">
    <Image {...part} />
  </div>
);

const UserMessage: FC = () => {
  return (
    <MessagePrimitive.Root
      data-slot="aui_user-message-root"
      className="fade-in slide-in-from-bottom-1 animate-in grid auto-rows-auto grid-cols-[minmax(72px,1fr)_auto] content-start gap-y-2 px-2 duration-150 [contain-intrinsic-size:auto_200px] [content-visibility:auto] [&:where(>*)]:col-start-2"
      data-role="user"
    >
      <UserMessageAttachments />

      <div className="aui-user-message-content-wrapper relative col-start-2 min-w-0">
        <div className="aui-user-message-content peer bg-muted text-foreground rounded-xl px-4 py-2 wrap-break-word empty:hidden">
          <MessagePrimitive.Parts
            components={{ File: UserFilePart, Image: UserImagePart }}
          />
        </div>
      </div>

      <div className="aui-user-action-bar-wrapper col-start-2 flex items-center justify-end gap-1 peer-empty:hidden">
        <UserActionBar />
      </div>

      <div className="col-span-full col-start-1 row-start-3 flex items-center justify-end gap-2">
        <MessageTimestamp />
        <BranchPicker data-slot="aui_user-branch-picker" className="-me-1" />
      </div>
    </MessagePrimitive.Root>
  );
};

const UserActionBar: FC = () => {
  return (
    <ActionBarPrimitive.Root
      hideWhenRunning
      autohide="not-last"
      className="aui-user-action-bar-root text-muted-foreground animate-in flex gap-1 duration-200"
    >
      <MessageCopyButton className="aui-user-action-copy" />
      <ActionBarPrimitive.Edit asChild>
        <TooltipIconButton tooltip="Edit" className="aui-user-action-edit">
          <PencilIcon />
        </TooltipIconButton>
      </ActionBarPrimitive.Edit>
      <RememberThisButton />
    </ActionBarPrimitive.Root>
  );
};

// getmaipai/home#60: assistant-ui never threads an edit's original
// message id into chatModelAdapter.ts's ChatModelRunOptions (the only
// place that carries it, `composer.send`'s own event, fires from a
// MESSAGE-scoped composer client - a listener outside this component's
// own subtree never receives it, confirmed live even with `{ scope: "*"
// }`), so this is computed and stashed here instead, from inside the one
// component that already sits in that message's own scope. `s.thread.
// messages` is the CURRENTLY DISPLAYED branch, so the entry right after
// this message is the turn's own reply, and chatModelAdapter.ts's "done"
// yield now stamps every live reply's real turnId onto that entry too -
// resolves for a message edited moments after sending, not only one
// already reloaded from history. Read at SEND time (inside the Update
// button's own onClick, composed to run before assistant-ui's real send
// callback - createActionButton's composeEventHandlers(primitiveProps.
// onClick, callback) - never at render time: the messages list is
// otherwise stale by the moment a person actually clicks).
const EditComposer: FC = () => {
  const editedMessageId = useAuiState((s) => s.message.id);
  const messages = useAuiState((s) => s.thread.messages);
  const handleSendClick = () => {
    const editedIndex = messages.findIndex((m) => m.id === editedMessageId);
    const reply = editedIndex >= 0 ? messages[editedIndex + 1] : undefined;
    const turnId = reply?.role === "assistant" ? (reply.metadata?.custom?.turnId as string | undefined) : undefined;
    setPendingSupersedes(turnId ?? null);
  };
  return (
    <MessagePrimitive.Root
      data-slot="aui_edit-composer-wrapper"
      className="flex flex-col px-2 [contain-intrinsic-size:auto_200px] [content-visibility:auto]"
    >
      <ComposerPrimitive.Root className="aui-edit-composer-root border-border/60 dark:border-muted-foreground/15 ms-auto flex w-full max-w-[85%] cursor-text flex-col rounded-(--composer-radius) border bg-(--composer-bg)">
        <ComposerPrimitive.Input
          className="aui-edit-composer-input text-foreground min-h-14 w-full resize-none bg-transparent px-4 pt-3 pb-1 text-base outline-none"
          autoFocus
        />
        <div className="aui-edit-composer-footer mx-2.5 mb-2.5 flex items-center gap-1.5 self-end">
          <ComposerPrimitive.Cancel asChild>
            <Button
              variant="ghost"
              size="sm"
              className="h-8 rounded-full px-3.5"
            >
              Cancel
            </Button>
          </ComposerPrimitive.Cancel>
          <ComposerPrimitive.Send asChild onClick={handleSendClick}>
            <Button size="sm" className="h-8 rounded-full px-3.5">
              Update
            </Button>
          </ComposerPrimitive.Send>
        </div>
      </ComposerPrimitive.Root>
    </MessagePrimitive.Root>
  );
};

const BranchPicker: FC<BranchPickerPrimitive.Root.Props> = ({
  className,
  ...rest
}) => {
  const turnId = useAuiState((s) => {
    const value = s.message.metadata?.custom?.turnId;
    return typeof value === "string" ? value : undefined;
  });
  const branchNumber = useAuiState((s) => s.message.branchNumber);
  const previousBranch = useRef<string | null>(null);
  useEffect(() => {
    const current = turnId ? `${turnId}:${branchNumber}` : null;
    if (previousBranch.current !== null && current !== previousBranch.current && turnId) {
      // assistant-ui owns the local branch cursor. Persist the selected
      // turn after that cursor moves so the next reload starts on the same
      // sibling and the next follow-up uses it as its parent.
      void api.chooseConversationTurn(turnId).catch(() => {});
    }
    previousBranch.current = current;
  }, [branchNumber, turnId]);
  return (
    <BranchPickerPrimitive.Root
      hideWhenSingleBranch
      // Deliberate type-floor exception (docs/UI.md, lane 7 item 3,
      // 2026-09-13): the "1 / 2" edited-message switcher, a compact
      // inline pagination control, the same category as a badge count.
      className={cn(
        "aui-branch-picker-root text-muted-foreground -ms-2 me-2 inline-flex items-center text-xs",
        className,
      )}
      {...rest}
    >
      <BranchPickerPrimitive.Previous asChild>
        <TooltipIconButton tooltip="Previous">
          <ChevronLeftIcon />
        </TooltipIconButton>
      </BranchPickerPrimitive.Previous>
      <span className="aui-branch-picker-state font-medium">
        <BranchPickerPrimitive.Number /> / <BranchPickerPrimitive.Count />
      </span>
      <BranchPickerPrimitive.Next asChild>
        <TooltipIconButton tooltip="Next">
          <ChevronRightIcon />
        </TooltipIconButton>
      </BranchPickerPrimitive.Next>
    </BranchPickerPrimitive.Root>
  );
};
